### ISSUE TITLE
Clarification regarding PIX Manager creating a "resource id"

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#10]
In https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104413-expected-actions,
"the Patient Identifier Cross-reference Manager MAY create a resource id on a Conditional update/create but is not required to do so, there is no requirement on PIX Manager to managed identities, only to cross-correlate provided identifiers."

- Does this mean that the PIX Manager MAY create a Patient resource on the Conditional update? In this case I would suggest to clarify and replace "resource id" by "Patient resource".
- Or is "id" really meant here, in which case I will argue that a FHIR resource always have an id ([https://www.hl7.org/fhir/resource-definitions.html#Resource.id](https://www.hl7.org/fhir/resource-definitions.html#Resource.id ) "The only time that a resource does not have an id is when it is being submitted to the server using a create operation.")?
- Or in case by "id" you meant "identifier", then I will ask which domain are we talking about.

**Comment by oliveregger** [comment]
The meaning was the first bullet point and I think your clarification helps also for clarifying @lynnfel issue here: https://github.com/IHE/ITI.PIXm/issues/32, will change it, thanks
