### ISSUE TITLE
change IG id to lowercase

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.PIXm#109]
Sushi problem with IHE.ITI.PIXm uppercase package naming

**Issue** 
1. if an IG wants to include IHE.ITI.PIXm#3.0.0 sushi is not able to detect it, if the dependency is only provided in the implementation guide resources

```
Sushi: info  Downloaded IHE.ITI.PIXm#3.0.0                                       (00:02.0559)
Sushi: error Failed to load IHE.ITI.PIXm#3.0.0: The package IHE.ITI.PIXm#3.0.0 could not be loaded locally or from the FHIR package registry. (00:02.0577)
```
2. If an IG includes the dependency in sushi-config.yml, it works, but the following warning appears: 

```
sushi warning: package name with upper case letters discouraged
```

**Proposed Change** 
Rename package for next publication to ihe.iti.pixm (which would be similar to ihe.mhd.fhir)

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
need to capture guidance for future package name pattern. It was natural in IHE to use upper case for acronyms and such, so that is what I did. Unclear if future projects should tend to use lowercase only.

**Comment by oliveregger** [comment]
mhd is lowercase: ihe.mhd.fhir but we will switch for new ig's to uppercase except there is guidance on not using it.

**Comment by oliveregger** [comment]
see also https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename:
> Each package has a canonical name (a globally unique identifier). A package name consists of two or more namespaces separated by a dot. Each namespace starts with a lowercase alphabet character followed by zero-or-more lowercase alphanumeric characters or dashes.

**Comment by JohnMoehrke** [comment]
change id from IHE.ITI.PIXm to ihe.iti.pixm
