### ISSUE TITLE
Link for response message of Add or Revise Patient

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#11]
In [https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104414-response-message](https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104414-response-message):
_See http://hl7.org/fhir/http.html#create for response._

Why is the link referencing to the response of #create and not #cond-update?

**Comment by oliveregger** [comment]
thanks, agree that it is better to point to cond-update
