### ISSUE TITLE
Wrong reference in the Resolve patient duplicates Expected actions

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#15]
https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104423-expected-actions
"The Patient Identifier Cross-reference Manager shall be capable of accepting attributes in the Duplicates Resolved message as specified in 3.104.4.2.2.2.1." There is no such "Duplicates Resolved message nor section 3.104.4.2.2.2.1.

**Comment by oliveregger** [comment]
thanks, should point to 3.104.4.2.2.2.1, https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#231044221-patient-resource-constraints
