### ISSUE TITLE
Resolve Patient duplicate example: which Alice is the survivor?

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#17]
https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104425-example 
In the example, it is not clear which Alice is the survivor and which is the deprecated.

And again, why only updating the survivor?

**Comment by oliveregger** [comment]
@obellamouhuet I updated the example description, is it now clear?

**Comment by obellamouhuet** [comment]
@oliveregger Yes, it is much clearer now, thanks!
