### ISSUE TITLE
Optional/Mandatory support of messages in the Mobile Patient Identifier Cross-reference Feed [ITI-104]

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#18]
In https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#2310443-remove-patient, "The Patient Identifier Cross-reference Manager indicates in the CapabilityStatement if this message is supported.".

Why is this sentence only in the section Remove Patient? Is the Remove Patient optional and are the Add or Revise Patient and Resolve Patient duplicates mandatory to support? In that case, I believe it should be made clear in the document.

**Comment by oliveregger** [comment]
related to https://github.com/IHE/ITI.PIXm/issues/31

**Comment by oliveregger** [comment]
An error condition has been added in expected actions to indicate when the message is not supported, therefore the remove patient message is not optional anymore.

**Comment by oliveregger** [comment]
However I would argue that you still need to describe in the capability statement if you support the conditional delete or not, so the client could inquire if the conditional delete is working or not.

It is  correct that we are not mentioning this for the Resolve Patient, we have it for the Add/Revise section. Will add it there.

**Comment by obellamouhuet** [comment]
Nice, thanks!
