### ISSUE TITLE
Use case process flows "intentionally left blank" 

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#19]
https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/volume-1.html#14142-use-cases

In Vol 1 Use cases, I hope "blank" is a placeholder.   We should show the interaction diagrams for the use cases

**Comment by msmock** [comment]
refactored the use case section by adapting the use case from https://profiles.ihe.net/ITI/TF/Volume1/ch-5.html. See commit number fba93e9.
