### ISSUE TITLE
Use Case 1 & 2

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#20]
Use case 1: https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/volume-1.html#141421-retrieving-documents-from-other-domains

- It seems odd that the use case title is "retrieving documents from other domains".  It is really "finding a patient's ID in another domain (to enable retrieving documents)"
- The last sentence in this section is really the first thing that happens in time:  the patient is registered by the ADT to get an MRN.   Other things are also out-of-order.  Re-arrange the section so the events are chronological.  i.e. 1. ADT creates MRN. 2. allergy information is stored under that MRN, 3. Accident happens. 4. driver's license via ITI-104 5. PIX Mgr cross-references the IDs, 6. PIXm query & response, etc

Use case 2: https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/volume-1.html#141422-providing-documents-for-other-domains

I don't see the value of this use case for PIXm:

- The first sentence (providing documents) has nothing to do with PIXm
- The second sentence (PIXm query to enable retrieving a doc) is really use case 1

Is there a reason why we are just not reusing the Use cases from PIX? https://profiles.ihe.net/ITI/TF/Volume1/ch-5.html#5.3   (even if we copy them rather than referring to them...)

**Comment by msmock** [comment]
Copied the first use case (Multiple ID Domains in a Single Facility Process Flow) to the IG and converted the flow to plantuml. The other use case descriptions https://profiles.ihe.net/ITI/TF/Volume1/ch-5.html#5.3 do not seem to be relevant for PIXm, since they describe the update notification and PIX options.

**Comment by msmock** [comment]
refactored the use case section by adapting the use case from https://profiles.ihe.net/ITI/TF/Volume1/ch-5.html. See commit number fba93e9.
