### ISSUE TITLE
41.4.2: Vol 1 Use Cases

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#21]
- Consider moving Use Case 3 & 4 prior to Use Case 1 & 2.   This enables a reader to understand how the feed works between the Source & Manager, before reading how the cross-referenced IDs are used when the Consumer queries the Manager.
- In 3 & 4, clarify that the "patient administration" of the hospital is acting as the Source actor.
- In use case 4, add a sentence at the end that says, "This enables the Patient Identifier Cross-reference Manager to ...", just as you do in Use Case 3.  This enables the reader to know what the PIX Mgr does when resolving duplicates.

**Comment by msmock** [comment]
refactored the use case section by adapting the use case from https://profiles.ihe.net/ITI/TF/Volume1/ch-5.html. See commit number fba93e9.

**Comment by lynnfel** [comment]
I am reopening this.  I will provide separate comments on the use cases.

**Comment by oliveregger** [comment]
Usecase is goot, but needs to be adapted

(PIXm needs to be before MHD)
