### ISSUE TITLE
Name (and scope) of ITI-104 feed transaction

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#22]
PIX has Patient Identity Feed [ITI-8] and PIXV3 has Patient Identity Feed HL7V3 [ITI-44].

This profile has:
Mobile Patient Identifier Cross-reference Feed [ITI-104]

Is there a reason we included "Cross-reference" in the transaction name.  Do we only intend it to be used for cross-reference purposes?  If yes, then OK.    If we think it will be re-used in other profiles, then perhaps we should rename it.

**Comment by lynnfel** [comment]
Depending on whether this transaction is intended only as a feed to a PIX manager (for cross-referencing purposes), or whether it's intended as a more generic transaction, we may need to update  content in Roles and Expected actions, etc

**Comment by oliveregger** [comment]
The scope of the work item was to add a feed to the Cross-reference Manager. During the telcos it was decided to create a new transaction to differentiate it from the PMIR Mobile Patient Identity Feed transaction, therefore i think a reuse from other profiles might be unlikely.

**Comment by oliveregger** [comment]
we do an open issue that the transaction name might change and future discussion will be relative to the development in PMIR
