### ISSUE TITLE
Cross-profiles considerations with PMIR.

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#24]
Do we need a paragraph added to explain how the PMIR feed is distinguished from PIXm feed, and the environment in which each is appropriate?

Remember, too, that the PIXm Query transaction is also used in PMIR, so a PMIR Registry responds to ITI-83.    For the 2021 Connectathons, (where systems might support both PIX Mgr and PMIR Registry), I wrote explanatory text about how the ITI-83 response might look different in those two environments (https://gazelle.ihe.net/content/pmirconnectathontestpatients).  I haven't thought, yet, about whether that explanation will need to be updated when this newer PIXm profiles is published.

Maybe this is future whitepaper material, but it seems like a gap

**Comment by oliveregger** [comment]
add this at the explanation of the option issue, put the gazelle link into the open issue
