### ISSUE TITLE
ITI-78 responses vs ITI-9 and 45 responses

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#26]
PIXv2 query response has 6 cases https://profiles.ihe.net/ITI/TF/Volume2/ITI-9.html#3.9.4.2.2.6

So does ITI-45 PIXv3 query

PIXm query response had 3 cases.   Is this intentional?

**Comment by oliveregger** [comment]
according to @JohnMoehrke  this work was done to the during the original publication of pixm, they resolve to three responses
