### ISSUE TITLE
 Newer ITI-83 audit record def'n assumes FHIR Audit Event

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#27]
The PDF version of ITI-83 shows the differences from the v2 version of the same transaction in ITI-9.

In the IG https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-83.html#238351-security-audit-considerations, you assume FHIR AuditEvent format.

I don't think we should lose the diff with  PIX query audit v2.

**Comment by oliveregger** [comment]
we defined the complete audit event explicitly in the profile definition http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/StructureDefinition-IHE.PIXm.Query.Audit.Consumer.html, do we need to reiterate it in the text the differences to v2?

**Comment by oliveregger** [comment]
It was intensional to remove it and to follow the MHD pattern with the FHIR Audit Event profile and example defined.
