### ISSUE TITLE
2:3.104.4 Is "his" the Source?

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#28]
https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#231044-messages

A Patient Identity Source notifies the Patient Identifier Cross-reference Manager for adding or revising patients in **his patient identifier domain**. The Patient Identity Source notifies the Patient Identifier Cross-reference Manager that duplicate records were resolved in the Patient Identity Source. The Patient Identity Source may notify the Patient Identifier Cross-reference Manager that a patient record was removed in the Patient Identity Source

In the above, in the first sentence, I think you want to follow the pattern in the following two sentences, eg.. "
A Patient Identity Source notifies the Patient Identifier Cross-reference Manager that patient records were added or revised in the Patient Identity Source.

**Comment by oliveregger** [comment]
fixed, thanks

**Comment by lynnfel** [comment]
Your changes are close, but not quite....   the notification happens *after* some has happened on the Source, so,,,

I recommend changing this:
A Patient Identity Source notifies the Patient Identifier Cross-reference Manager for adding or revising patients in the Patient Identity Source. 

To this:
A Patient Identity Source notifies the Patient Identifier Cross-reference Manager that a patient has been added or revised in the Patient Identity Source. 

Here is the remainder of the paragraph
The Patient Identity Source notifies the Patient Identifier Cross-reference Manager that duplicate records were resolved in the Patient Identity Source. The Patient Identity Source may notify the Patient Identifier Cross-reference Manager that a patient record was removed in the Patient Identity Source.

**Comment by oliveregger** [comment]
thanks, i was just paying attention first to the bold part, not the second part, sorry.
