### ISSUE TITLE
ITI-104 resolve duplicates expected actions

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#29]
https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104423-expected-actions

The Patient Identifier Cross-reference Manager shall be capable of accepting attributes in the Duplicates Resolved message as specified in 3.104.4.2.2.2.1.   _<=== Not a valid section number_

The Patient Identifier Cross-reference Manager shall perform the Expected Actions similar to the ones specified in ITI TF-2: 3.8.4.2.3. The particular behavior is described below.  _<=== if the expected actions are 'similar' but not the same, what is the value of the reference??_

When the Patient Identifier Cross-reference Manager receives the Resolve Patient duplicate message of the Patient Identity Feed transaction, (_<=== match the message name exactly)_ ...

... it shall cross-reference the patient identifiers provided by replacing any references it is maintaining internally to the patient identifier provided in the ‘replaces’ link by the patient identifier included in the Patient resource. After the identifier references are replaced, the Patient Identifier Cross-reference Manager shall reapply its internal cross-referencing logic/ policies before providing the updated information via the PIX Query transactions.   (_<=== in the beginning of this text, you say it shall cross-reference...   but at the end, you say that  the cross-referencing happens after the identifier references are replaced.   I  think this text needs revision in committee.)_

**Comment by oliveregger** [comment]
> https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104423-expected-actions
> 
> The Patient Identifier Cross-reference Manager shall be capable of accepting attributes in the Duplicates Resolved message as specified in 3.104.4.2.2.2.1. _<=== Not a valid section number_


fixed with https://github.com/IHE/ITI.PIXm/issues/15


> The Patient Identifier Cross-reference Manager shall perform the Expected Actions similar to the ones specified in ITI TF-2: 3.8.4.2.3. The particular behavior is described below. _<=== if the expected actions are 'similar' but not the same, what is the value of the reference??_

good point, will remove the sentence
 
> When the Patient Identifier Cross-reference Manager receives the Resolve Patient duplicate message of the Patient Identity Feed transaction, (_<=== match the message name exactly)_ ...
> 
> ... it shall cross-reference the patient identifiers provided by replacing any references it is maintaining internally to the patient identifier provided in the ‘replaces’ link by the patient identifier included in the Patient resource. After the identifier references are replaced, the Patient Identifier Cross-reference Manager shall reapply its internal cross-referencing logic/ policies before providing the updated information via the PIX Query transactions. (_<=== in the beginning of this text, you say it shall cross-reference... but at the end, you say that the cross-referencing happens after the identifier references are replaced. I think this text needs revision in committee.)_

also related to issue https://github.com/IHE/ITI.PIXm/issues/16

**Comment by oliveregger** [comment]
last point will be closed with #16
