### ISSUE TITLE
Transaction number 104

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PIXm#3]
I have assigned the new PIXm feed to transaction number 104

https://wiki.ihe.net/index.php/ITI_Vocabulary_Registry_and_Data_Dictionary#Volume_2c.2C_Transaction_and_Section_Numbers

| ITI-104
| Patient Identity Mobile Feed

**Comment by lynnfel** [comment]
John

Rather than maintaining the wiki, we should just use Gazelle Master Model as the authoritative source of already-allocated transaction number:  https://gazelle.ihe.net/GMM/tf/transaction/listTransactions.seam

**Comment by JohnMoehrke** [comment]
Lynn, the co-chairs have no administrative rights to add transaction numbers to GMM. This would not be possible to change the process until that is supported.

**Comment by oliveregger** [comment]
@JohnMoehrke could you adjust the transaction name on the wiki? i'm not autorized to do changes on the wiki.

**Comment by JohnMoehrke** [comment]
Note that the transaction and actor name do end up in gazelle and that is what is used in our html publication.... The wiki is used for record keeping of "what is the next transaction number available"
