### ISSUE TITLE
Vol 1 sentence in ITI-104 trigger events

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#30]
https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104431-trigger-events

For a given Patient Identifier Domain there SHALL be one and only one Patient Identity Source Actor, but a given Patient Identity Source may serve more than one Patient Identifier Domain.

Move the above sentence to Vol 1, perhaps here: https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/volume-1.html#141111-patient-identifier-cross-reference-source

**Comment by oliveregger** [comment]
during the last call we discussed to have it for each message repeated, we can move it also to vol1, discuss today at meeting?

**Comment by oliveregger** [comment]
replace occurence in volume 2 (three times)
add it to 1:41.1.1.1 Patient Identifier Cross-reference Source
replace link in volume 1 with cross-reference for the defintiion of pix manager
