### ISSUE TITLE
ITI-104 for PIX Mgrs who don't support Remove

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#31]
https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#2310443-remove-patient says "The Patient Identifier Cross-reference Manager indicates in the CapabilityStatement if this message is supported."

Usually the server has to support all messages in a transaction, but,  if this is truly 'optional', then the Expected Actions should have some indication of what a PIX Manager should send back to the Consumer to indicate that it's not going to respond to the Remove notification.   

...OR... does this imply that the Source has to know (via the Manager's Capability Stmt) that the server doesn't support remove, so it shouldn't send this message???

**Comment by oliveregger** [comment]
1. v2 and v3 don't know this message type, so if this message is not optional a grouping with v2, v3 actors could not be done
2. an expected action needs to be added, this is a good point
