### ISSUE TITLE
Explicit link request from a Source

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#35]
"This profile does neither specify the rules and algorithm applied by the Patient Identifier Cross-reference Manager actor to link or unlink the patient identity data from different domains, nor the point in time the Patient Identifier Cross-reference Manager actually links the data. Patient Identifier Cross-reference Manager may link the patient identity data from the different domains on time of the Mobile Patient Identifier Cross-reference Feed [ITI-104] transactions, but also _**may provide other triggers (e.g., manual linking or unlinking in case when the rules and algorithms go wrong).**_"

Does this include that a Source can explicitly request the PIX Manager to perform a link of two patients? 

As an example where it can be needed, let's say we have system A in domain A, system B in domain B (system B is both PIX Source and Consumer), and a PIX Manager.
System A sends a patient referral to system B for a patient P1. P1 has an identifier from domain A. 
System B, which does not recognize the identifier from domain A, sends a PIX query to the PIX manager to find existing patients in domain B linked to patient P1.
If the request does not return any patient, system B will create a new patient P2 with the demographics from P1 and an identifier from domain B. 
System B will then inform the PIX Manager of the newly created patient P2 via the patient identity feed (ITI-104).
**=> Can system B explicitly ask the PIX Manager to link P1 and P2?** 
The PIX Manager is expected to notice that P1 and P2 are the same patient and link them, but can an external system trigger the link in case the rules and algorithms go wrong? 
And would that be part of the PIXm transactions?

**Comment by oliveregger** [comment]
This is not a Usecase covered in PIXm because the PIXm feed is about notifying from one domain and leaving the cross-referencing logic at the PIX Manager. If the Cross-reference Managers allows multiple identifiers in the feed (eg. System B would send an update with including the identifier from domain A) and has the rule to use this a cross-referencing method then that use case can be realised with the existing add/revise message.

**Comment by obellamouhuet** [comment]
Thank you for the answer, I needed confirmation. I will close the issue now.
