### ISSUE TITLE
Linking based on the data provided by ITI-104

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#36]
In https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/volume-1.html#14141-concepts:
"This profile assumes that the Patient Identifier Cross-reference Manager performs linking and unlinking based on the patient identity data provided in the Mobile Patient Identifier Cross-reference Feed [ITI-104] transactions from different patient domains."

I don't think the linking/unlinking is done only from the data from ITI-104, as linking and unlinking was already performed in the previous version of PIXm. Why would we limit the linking/unlinking to the data from ITI-104?

**Comment by msmock** [comment]
The reason is, that the Patient Identifier Cross-reference Manager of the PIXm profile only publishes the ITI-104 to retrieve patient identity data used for cross referencing. Other transaction may be supported by grouping with other actors. From my point of view, that is out of scope of the section. But I'm open for any suggestions of how to refine the text.

**Comment by BenLevy62** [comment]
I think she's right.  You could remove that sentence and lose nothing pertinent.  Plus there's nothing stopping the Manager from getting information in ways not covered by IHE profiles at all.  There should be nothing preventing that.  And while that sentence doesn't contain a shall, it is putting that idea out there.

**Comment by obellamouhuet** [comment]
@msmock I do not deny that the data from ITI-104 is used for the linking/unlinking, I just meant that the sentence seems to limit the linking/unlinking to only data from ITI-104, while you can have other mechanisms to trigger the link/unlink.

**Comment by JohnMoehrke** [comment]
I agree with @obellamouhuet we should not be overly specific about what magic the pix manager uses for cross-referenceing. We do provide the details in the feed, but that is not the sole data that a pix manager is allowed to use for linking.

**Comment by JohnMoehrke** [comment]
I think this was removed in https://github.com/IHE/ITI.PIXm/commit/b03d18b853a25db2d66d3f429d819ddfc861fcba
