### ISSUE TITLE
2:3.104.4.2.1 Trigger Events

### ISSUE THREAD

**Issue by BenLevy62** [IHE/ITI.PIXm#38]
Move this first sentence above to 2:3.104.4.2:  The Resolve Patient duplicate trigger signals that duplicate records were resolved in the Patient Identity Source.

**Comment by oliveregger** [comment]
i think the sentence should stay in the trigger event section, but would suggest to add to 2:3.104.4.2 as an introduction:

The Patient Identity Source notifies the Patient Identifier Cross-reference Manager that duplicate records were resolved in the Patient Identity Source.

**Comment by oliveregger** [comment]
The Resolve Duplicate Patient trigger signals that duplicate records were resolved in the Patient Identity Source.

A Resolve Duplicate Patient message indicates that the Patient Identity Source has done a merge within a specific Patient Identification Domain. That is, the surviving patient identifier has subsumed a duplicate patient identifier.



remote the first sentence
reword the second sentence:

A Resolve Duplicate Patient message is triggered when the Patient Identity Source does a merge within a specific Patient Identification Domain.

The Add Patient trigger event signals that a new patient was added to a Patient Identity Source.
-> The Add Patient message is triggered when a new patient is added to a Patient Identity Source.

The Revise Patient trigger event signals that patient information was revised in a Patient Identity Source (e.g., change in patient name, patient address, etc.).

-> The Revise Patient message is triggered when the patient information is revised within a Patient Identity Source (e.g., change in patient name, patient address, etc.).
