### ISSUE TITLE
HL7 IG covering FHIR ADT

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PIXm#4]
We should understand and document how PIXm solution compares and contrasts to DaVinci Alerts IG.

http://hl7.org/fhir/us/davinci-alerts/STU1/index.html

**Comment by oliveregger** [comment]
architecture: one main difference is that the DaVinci Alerts IG is defining FHIR messages where as PIXm is proposing a FHIR RESTFul interaction
usecase: ADT vs Patient Identifier Cross-referencing

**Comment by oliveregger** [comment]
@JohnMoehrke can we close this or does this need further discussion
