### ISSUE TITLE
3.104.4.2.2.1 Patient Resource constraints

### ISSUE THREAD

**Issue by BenLevy62** [IHE/ITI.PIXm#40]
In this sentence, change "duplicate" to "subsumed."   A link of type 'replaces' SHALL be added with the identifier pointing to the _duplicate_ record.

**Comment by oliveregger** [comment]
this changed already with the switch to replaced-by to:

A link of type 'replaced-by' SHALL be added with the identifier pointing to the surviving patient identifier, see https://www.hl7.org/fhir/patient.html#dup-records.

is that ok like this? see http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#231044221-patient-resource-constraints
