### ISSUE TITLE
2:3.104.4.2.3 Expected Actions - What does the link point to?

### ISSUE THREAD

**Issue by BenLevy62** [IHE/ITI.PIXm#41]
We say this in 4.2.3:  The Patient Identifier Cross-reference Manager shall be capable of accepting attributes in the Duplicates Resolved message as specified in 2:3.104.4.2.2.1.   

But looking in that section, what attributes are we talking about?  The link type?  If that's it, this is just noise to me.

**Comment by oliveregger** [comment]
agree, will remove the section and put it above
