### ISSUE TITLE
2:3.104.4.2.5 Example

### ISSUE THREAD

**Issue by BenLevy62** [IHE/ITI.PIXm#42]
We say here that Maiden has been merged into Mohr.  Everywhere else it's backwards to that:  x has been subsumed by y.  It's like a tense shift.  Please use one direction.

Also, the duplicate identifier should be the subsumed identifier.

**Comment by oliveregger** [comment]
thanks for the corrections

**Comment by oliveregger** [comment]
Patient Maiden Alice has been subsumed by Patient Mohr Alice in the Patient Identifier Domain urn:oid:1.3.6.1.4.1.21367.13.20.1000. The HTTP conditional update operation is done with the subsumed identifier ‘IHERED-m94’ from Maiden Alice in the request and referencing the surviving identifier ‘IHERED-994’ of Patient Mohr Alice in the message:

http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#2310442-resolve-duplicate-patient
