### ISSUE TITLE
2:3.104.4.3.3 Expected Actions

### ISSUE THREAD

**Issue by BenLevy62** [IHE/ITI.PIXm#43]
Suggest changing this:

When the Patient Identifier Cross-reference Manager receives the Remove Patient message of the Patient Identity Feed transaction, it shall cross-reference the patient identifiers provided by removing any references it is maintaining internally to the patient identifier provided.

to this:

When the Patient Identifier Cross-reference Manager receives the Remove Patient message, it shall remove any references it is maintaining internally to the patient identifier provided.

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104433-expected-actions
