### ISSUE TITLE
2:3.104.4.3.3 Expected Actions

### ISSUE THREAD

**Issue by BenLevy62** [IHE/ITI.PIXm#44]
Suggest changing this:

After the identifier references are replaced, the Patient Identifier Cross-reference Manager shall reapply its internal cross-referencing logic/ policies before providing the updated information via the PIX Query transactions.

to this:

After processing the Remove Patient message, the Patient Identifier Cross-reference Manager shall not return the removed identifier in response to PIX Query transactions.

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104433-expected-actions
