### ISSUE TITLE
Revision question

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.PIXm#46]
I set the revision to 2.2, the current PDF is 2.1.... I could be convinced that because of the feed, this should actually be published as 3.0...

Note that publishing it as 3.0 would be what we do AFTER we resolve comments and publish for TI.

That said, we should agree on the intended version plan.

**Comment by oliveregger** [comment]
after public comment would be 3.0 as intended
for public comment it would be 2.2 (it would be nice to have 3.0.0-publicomment)
