### ISSUE TITLE
Missing IHE IUA scopes for ITI83 and ITI104

### ISSUE THREAD

**Issue by joostreuzel** [IHE/ITI.PIXm#49]
**Section Number** 1:41.5

**Issue** Recommended OAuth scopes missing for use with IHE IUA. IHE IUA intentionally does not provide the OAuth2 scopes for all interactions, and leaves that to the profiles that reference IHE IUA. In the current form of the profiles no scopes are defined for the transactions in PIXm, potentially leading to non-interoperability on security level.

**Proposed Change** Add scopes based on transaction ids for use with IHE IUA. `ITI-83` for query API methods, `ITI-104` for the feed API methods. These should be added to section 2:3.83.5 and section 2:3.104.5 respectively. This approach is similar to what was [done for the IHE MHD profile](https://profiles.ihe.net/ITI/IUA/index.html#33-mhd-profile).

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by oliveregger** [comment]
decisiton at the telco: will add those to the security section as proposed

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/IHE/ITI.PIXm/branches/iua_scopes/index.html
