### ISSUE TITLE
1:41.1.1.3 - suggested improvement to wording

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#53]
**Section Number** 1:41.1.1.3 https://profiles.ihe.net/ITI/PIXm/volume-1.html#141113-patient-identifier-cross-reference-manager

**Issue** slight rewording suggestion below

**Proposed Change** 
Suggest changing this:
The Patient Identifier Cross-reference Manager manages patient identity data from different domains and cross-references patient identity data from different domains assigned to the same patient person.

To this:
The Patient Identifier Cross-reference Manager manages patient identity data from different domains and cross-references patient identity data from different domains for the same patient.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
will adjust wording
