### ISSUE TITLE
1:41.3 - add Source to grouping table

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#54]
**Section Number** 1:41.3 https://profiles.ihe.net/ITI/PIXm/volume-1.html#1413-pixm-required-actor-groupings

**Issue**  Add Source actor to required grouping table

**Proposed Change** see above

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
thanks for catching that!
