### ISSUE TITLE
1:41.4.1 - back-reference to PIX rqmts is not specific enough

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#56]
**Section Number** 1:41.4.1 https://profiles.ihe.net/ITI/PIXm/volume-1.html#14141-concepts

**Issue**  We rely on PIX  define 'domain requirements' but when I followed the link to the PIX Vol 1 header, I didn't realize that the definition was a bit down in the introduction, so I initially assumed it was an inaccurate link.

**Proposed Change** 
"The requirements on Patient Identifier Domain and a Patient Identifier Cross-reference Domain as defined for the PIX profile apply also for this profile.  See [ITI TF-1 Figure 5-1](https://profiles.ihe.net/ITI/TF/Volume1/ch-5.html) and accompanying text."

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
thanks, will adjust that
