### ISSUE TITLE
Patient Identity Domain vs Patient Identifier domain

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#58]
**Section Number**  several

**Issue** use consistent terminology

**Proposed Change** 
I did not search the entire IG for uses of Patient Identity Domain vs Patient Identifier Domain
One example...  
In https://profiles.ihe.net/ITI/PIXm/volume-1.html#14141-concepts we say "The requirements on Patient Identifier Domain and a Patient Identifier Cross-reference Domain..."

In https://profiles.ihe.net/ITI/PIXm/volume-1.html#141421-multiple-identifier-domains-within-a-single-enterprise we say "This use-case has two Patient Identity Domains"

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by lynnfel** [comment]
Also, in ITI-104, we sometimes use "Patient Identification Domains" as a 3rd alternative

**Comment by oliveregger** [comment]
In https://profiles.ihe.net/ITI/TF/Volume1/ch-5.html we have one mention of Patient Identity Domain and 13 mentions (+3 in graphics) for Patient Identifier Domain. Patient Identifier Domain is explained,  Patient Identity Domain not. In https://profiles.ihe.net/ITI/TF/Volume1/ch-23.html#23 we have one mention of Patient Identifier Cross-reference Domains.

Suggest to switch everywhere to Patient Identifier Domain and remove  Patient Identity Domain. Also  remove Patient Identifier Cross-reference Domain from above mentioned sentence.
