### ISSUE TITLE
1:41.4.2.1.1 - don't refer to "link" ??

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#59]
**Section Number** 1.41.4.2.1.1 https://profiles.ihe.net/ITI/PIXm/volume-1.html#1414211-use-case-description
(and probably elsewhere...in other issues where I reworded text, I tried to remove 'link'

**Issue** I think that Ben does not want us to casually use the word "link" (check with Ben)

**Proposed Change** 
When the Patient Identifier Cross-reference Manager receives the Patient Identity Feed transactions, it performs its internal logic [02] and [04]to determine which patient identifiers can be **“linked”** as representing the same patient person based on the information included in the Feed transactions it has received. The cross-referencing process (algorithm, human decisions, etc.) is performed within the Patient Identifier Cross-reference Manager and is outside the scope of IHE.

...maybe because it is quoted, it's ok, but check with Ben

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by oliveregger** [comment]
@lynnfel do you contact Ben or do we do that a telco call?

**Comment by lynnfel** [comment]
I did not contact Ben.   Would we discuss this at the virtual face-to-face?
