### ISSUE TITLE
1:41.4.2.1.1 - suggested improvement in use case description

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#60]
**Section Number** 1:41.4.2.1.1 https://profiles.ihe.net/ITI/PIXm/volume-1.html#1414211-use-case-description

**Issue** suggestions for better description of pix query

**Proposed Change** 
The Intensive Care system wants to get lab information associated with a patient that the Intensive Care system knows as patient ID = MC-123. Using its own patient ID = MC-123, requests that PIXm Manager return the patient's ID in the Main Hospital domain [05].  Having previously cross-referenced this patient with a patient known by medical record number (e.g., 007) in the Main Hospital Domain [04], the PIXm Manager returns that identifier for the patient. The Intensive Care system is now able to request laboratory results via MHD [06], using the Patient Identifier in the Main Hospital Domain. The lab system finds lab documents and returns them to the Intensive Care system.

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
@lynnfel this is low priority in the sense that your better description can be integrated?

**Comment by lynnfel** [comment]
I marked low priority because I didn't think it needed discussion.
