### ISSUE TITLE
1:41.4.2.2 - fix typo and wording

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#61]
**Section Number** 1:41.4.2.2 https://profiles.ihe.net/ITI/PIXm/volume-1.html#141422-update-patient-identity-data-in-multiple-identifier-domains

**Issue** fix a typo and slight improvement suggestion below

**Proposed Change** 
Replace this:
This use-case shows the PIXm process when a retuning patient has different Identifying characteristics (identifiers, demographics, contacts, etc).

With this:
This use-case shows the PIXm process when an existing patient has updates to her identifying attributes (identifiers, demographics, contacts, etc).
or
This use-case shows the PIXm process when an existing patient has updates to her patient identity (identifiers, demographics, contacts, etc).

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
thx!
