### ISSUE TITLE
1:41.4.2.3 - suggestions for Resolve Duplicates use case

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#63]
**Section Number** 1:41.4.2.3 https://profiles.ihe.net/ITI/PIXm/volume-1.html#141423-resolve-duplicate-patient-identity-data-in-multiple-identifier-domains

**Issue** suggested edits for clarity below

**Proposed Change** 
Recommend replacing this:
1:41.4.2.3 Resolve duplicate patient identity data in Multiple Identifier Domains
When a duplicate patient identity is determined, and after the identity (and data) are merged/linked; the PIXm Manager is notified.
1:41.4.2.3.1 Use Case Description
The hospital main patient registration system had initially feeded the patient identity data to the Patient Identity Cross-reference Manager as patient persons entered the hospital for treatment [01].
After treatment the main patient registry system detects that the Charles 112 patient person was already registered with different patient identity data of Charlie 111. For example the Charles patient identity created on this episode may have had a typo in name, or different contact data). The hospital patient registration system marks the Charles patient identity data as duplicate, with preference for Charlie within the Main Hospital domain.
The hospital patient registration system updates the patient identity data by sending an Resolve Duplicate message to the Patient Identifier Cross-reference Manager using the Mobile Patient Identity Feed [ITI-104] transaction [09]. This transaction tells the PIXm Manager that the Charles should be deprecated in preference for Charlie 111 patient.
The PIXm Manager can now do further cross-referencing using internal logic [10].

With this:
1:41.4.2.3 Resolve duplicate patient identity data in Multiple Identifier Domains
When a Source determines that two patient identities exist for the same person, the Source merges/links the identities (and data), and then notifies the PIXm Manager.
1:41.4.2.3.1 Use Case Description
The Main Hospital patient registration system had initially added patient identity data to the PIXm Manager for both Charlie 111 [01] and Charles 112 [01] to the Patient Identity Cross-reference Manager.
After treatment, the registration system detects that Charles 112  was previously registered as Charlie 111. For example the Charles patient identity created on this episode may have had a typo in name, or different contact data). [ should we omit the preceding sentence?]  The registration system marks the Charles patient identity data as duplicate, with preference for Charlie within the Main Hospital domain.
The  registration system sends a Resolve Duplicate message to the Patient Identifier Cross-reference Manager using the Mobile Patient Identity Feed [ITI-104] transaction [09]. This transaction tells the PIXm Manager that the Charles 112 should be deprecated with preference for Charlie 111.   [do we want to use ‘deprecated’ here??]
The PIXm Manager can now do further cross-referencing using internal logic [10].

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
[do we want to use ‘deprecated’ here??] -> use subsumed with
