### ISSUE TITLE
Discrepancies in actor definitions between Gazelle Master Model and PIXm

### ISSUE THREAD

**Issue by MaryLJ** [IHE/ITI.PIXm#65]
**Section Number** Various locations in document

**Issue** Actor definitions in PIXm differ from Gazelle Master Model.

 
**Patient Identifier Cross-reference Consumer:**
- GMM:  This actor allows a system in a Patient Identification Domain to find out the identification of a patient in a different Patient Identification Domain by using the services of a Patient Identity Cross-Reference Manager Actor.
- PIXm: The Patient Identifier Cross-reference Consumer queries the patient ID lists from the Patient Identifier Cross-reference Manager. 

**Patient Identifier Cross-reference Manager:**
- GMM: Serves a well-defined set of Patient Identification Domains. Based on information provided by in each Patient Identification Domain by a Patient Identification Source Actor, it manages the cross-referencing of patient identifiers across Patient Identification Domains.
- PIXm: The Patient Identifier Cross-reference Manager manages patient identity data from different domains and cross-references patient identity data from different   domains assigned to the same patient person. 

**Patient Identifier Cross-reference Source:**
- Not in Gazelle (see issue #64 )
- PIXm: The Patient Identifier Cross-reference Source is the producer and publisher of patient identity data.

**Patient Identity Source**
- GMM: Each Patient Identification Domain requires this Actor to assign patient identities and to notify a Patient Identity Cross-reference Manager Actor of all events related to patient identification (creation, update, merge, etc.). For example, the Registration (ADT) Actor defined by the radiology Scheduled Workflow Profile would likely be a Patient Identity Source.
- PIXm Table 2:3.104.2-1 Actor Roles: Provides notification to the Patient Identifier Cross-reference Manager for any patient identification related events including: creation, updates, merges, etc. 

**Proposed Change** 
Decide which of the definitions is desired and either update GMM (at TI publication) or PIXm.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by oliveregger** [comment]
see also #52

**Comment by oliveregger** [comment]
John: An actor should have one definition independent of the profile.

We need to look at PIX, PIX V3 and PIXm actor and compare them: https://gazelle.ihe.net/GMM/tf/actor/listActors.seam

**Comment by oliveregger** [comment]
For discussion see summary on https://docs.google.com/spreadsheets/d/1Twc-uymtMF1oBSDuPIyrko9Oe41pb9deAbZFSS6EUfk/edit#gid=1735325675 :

- Actor definition in PIX and PIX V3 are done in Volume 2 and **differ by transaction** (_no volume actor 1 definition_)
- GMM uses more abstracts actor definitions than used in Volume 2
- Actor definitions between PIXm and PIX are only slightly different.

In PIXm we have in Volume 1 a line introducing the actor, might this be the place where the actor should correspond to the GMM actor definition?
