### ISSUE TITLE
2:3.83.1 - ITI-83 vs. ITI-9 scope

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#66]
**Section Number** 2:3.83.1 https://profiles.ihe.net/ITI/PIXm/ITI-83.html#23831-scope

**Issue** Reconcile the differences in the Scope of the PIX v2 and PIXm Query transactions.

**Proposed Change** 
Except, perhaps for the word 'immediately, I think I prefer the wording on ITI-9 scope.  Why not just refer to it (as ITI-45 does)?

ITI-9 PIX scope: This transaction involves a request by the Patient Identifier Cross-reference Consumer for a list of patient identifiers that correspond to a patient identifier known by the consumer. The request is received by the Patient Identifier Cross-reference Manager. The Patient Identifier Cross-reference Manager immediately processes the request and returns a response in the form of a list of corresponding patient identifiers, if any.

ITI-45 PIXv3 scope: The scope is identical to ITI TF-2: 3.9.1 , PIX Query Scope. 

ITI-83 PIXm query scope: This transaction is used by the Patient Identifier Cross-reference Consumer to solicit information about patients whose Patient Identifiers cross-match with a Patient Identifier it provides in the request message. The request is received by the Patient Identifier Cross-reference Manager. The Patient Identifier Cross-reference Manager processes the request and returns a response that includes zero or more Patient Identifiers for the matching patient.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by oliveregger** [comment]
the original text is the same as is in the pdf version, i don't know the background why the IT-83 scope changed.

**Comment by lynnfel** [comment]
ITI-83 scope updated to match the HL7v2 and v3 PIX queries:

This transaction is used by the Patient Identifier Cross-reference Consumer to solicit information about patients whose Patient Identifiers cross-match with a Patient Identifier it provides in the request message. The request is received by the Patient Identifier Cross-reference Manager. The Patient Identifier Cross-reference Manager processes the request and returns a response that includes zero or more Patient Identifiers for the matching patient.
