### ISSUE TITLE
Table 2:3.83.4.1.2-1 - fix typo

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#68]
**Section Number** https://profiles.ihe.net/ITI/PIXm/ITI-83.html#2383412-message-semantics in the _format row of the table...

**Issue** now that we have HTML publication, we don't have Vol 2x anymore

**Proposed Change** 
Change:  
See ITI TF-2x: Appendix Z.6

To:
See ITI TF-2: Appendix Z.6.  

Then, search the IG for other instances of this, (eg there is also one in https://profiles.ihe.net/ITI/PIXm/ITI-83.html#23834121-source-patient-identifier-parameter)

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
thx, will adjust all occurrences.
