### ISSUE TITLE
3:83.4.1.3 - Patient Identifiers vs Patient Identities

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#69]
**Section Number** 3:83.4.1.3 https://profiles.ihe.net/ITI/PIXm/ITI-83.html#2383413-expected-actions

**Issue** Sec 3.83.4.1.2.1 and 4.83.4.1.2.2 use "Patient Identifiers", but 3.83.4.1.3 uses "Patient Identities" for the same concept.

**Proposed Change** 
In the following text from 3.83.4.1.3, I think "Patient Identities" which I marked in Italics should be changed to "Patient Identifiers":

The Patient Identifier Cross-reference Manager shall use the sourceIdentifier and the targetSystem to determine the _Patient Identities_ that match, where _Patient Identities_ include business identifier(s) and the Logical id(s) of FHIR Patient Resource(s).

Response returned encoding and semantics is defined in Section 2:3.83.4.2:

The _Patient Identities_ returned may be a subset based on policies that might restrict access to some _Patient Identities_. For guidance on handling Access Denied, see ITI TF-2x: Appendix Z.7.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
thx, will adjust it.
