### ISSUE TITLE
editorial:  upper or lower case shall

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#70]
**Section Number** various

**Issue** in ITI-104, there is a mix of "SHALL" and "shall"

This also applies to "MAY" "may"

**Proposed Change**  
I have no preference for which is chosen, but be consistent across the IG.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
iti-83 uses all lower case, therefore change everything to lowercase (mhd uses also lowercaseI.

**Comment by oliveregger** [comment]
https://profiles.ihe.net/ITI/TF/Volume1/ch-23.html -> all lowercase
https://profiles.ihe.net/ITI/TF/Volume2/ITI-44.html, https://profiles.ihe.net/ITI/TF/Volume2/ITI-45.html -> mixed shall and SHALL, is there a rule?
