### ISSUE TITLE
Where can I find "$pixm operation"?

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#73]
**Section Number** http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/a_issues.html

**Issue** *The list of significant changes includes: Volume 2 ITI-83
Added Parameter StructureDefinitions for $pixm operation. However the volume 2 ITI-83 page does not mention any $pixm operation. The Artifacts section only refers to $match operation.*

**Proposed Change** *Indicate where is the updated definition of $pixm operation.*

**Priority**: *Low*

**Comment by obellamouhuet** [comment]
In http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-83.html there is only a $ihe-pix, that does not have a parameter StructureDefinition.

**Comment by oliveregger** [comment]
thanks, the naming need to be adjusted, that is a copy paste, left over.
$pim operation -> should be $ihe-pix
artifact $match -> should be $ihe-pix
