### ISSUE TITLE
 2:3.104.4.2.3 - suggested improvement to expected actions on merge

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#76]
**Section Number** 2:3.104.4.2.3 https://profiles.ihe.net/ITI/PIXm/ITI-104.html#23104423-expected-actions

**Issue** minor suggestion for clarity...

**Proposed Change** 
_Perhaps replace this:_
When the Patient Identifier Cross-reference Manager receives the Resolve Duplicate Patient message it shall replace any references it is maintaining internally to the patient identifier in the Patient resource with the patient identifier in the ‘replaced-by’ link.

_With this:_
When the Patient Identifier Cross-reference Manager receives the Resolve Duplicate Patient message, it shall replace any references it is maintaining internally to the subsumed patient identifier with the patient identifier in the ‘replaced-by’ link.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
thx for the suggestion, will incorporate it
