### ISSUE TITLE
editorial:  update references to Vol 2x

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#78]
**Section Number** 
https://profiles.ihe.net/ITI/PIXm/OperationDefinition-IHE_PIXm_pix.html
perhaps elsewhere

**Issue** when the ITI TF was published in HTML, Vol 2x vanished.  It is now just of Vol 2

**Proposed Change** *
Search/replace references to Vol 2x.

eg on https://profiles.ihe.net/ITI/PIXm/OperationDefinition-IHE_PIXm_pix.html,  change "ITI TF-2x: Appendix E.3" to "ITI TF-2: Appendix E.3"    There is another one on that page.

Do this across the IG.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
fixed with #68
