### ISSUE TITLE
Cardinality of assigner in PIXm Query Params Out

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.PIXm#81]
**Section Number** https://profiles.ihe.net/ITI/PIXm/StructureDefinition-IHE.PIXm.Query.Parameters.Out.html

**Issue** In a PIXm Query  query response assigner in targetIdentifier should have cardinality 0..1

**Proposed Change** 
See link above for Out parameters on the query.

Somewhere in the IG I read (I think) that in the query response, assigner is optional, but if it is sent, you shall send name.    If so, then change cardinality for assigner to 0..1 in the StructureDefinition
**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by oliveregger** [comment]
assigner is 0..1 but it is not listed in the differential (but the snapshot has 0..1), but i think we can adjust it, that is also shown in the differential.
